version: '2'
services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'development_railsgoat'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    expose:
      - '3306'
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root"]
      interval: 5s
      timeout: 10s
      retries: 3

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: mysql
      DB_USERNAME: root
      DB_PASSWORD:
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql

